name: Deploy DAGs to Airflow

on:
  push:
    branches:
      - main  # יתבצע בכל push ל-main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload DAGs to Airflow
        run: |
          for file in dags/*.py; do
            curl -X PUT "${{ secrets.AIRFLOW_URL }}/api/v1/dags/$(basename $file .py)/dagCode" \
                 --user "${{ secrets.AIRFLOW_USER }}:${{ secrets.AIRFLOW_PASSWORD }}" \
                 -H "Content-Type: text/plain" \
                 --data-binary @"$file"
          done

      - name: Refresh DAGs in Airflow
        run: |
          for file in dags/*.py; do
            curl -X POST "${{ secrets.AIRFLOW_URL }}/api/v1/dags/$(basename $file .py)/refresh" \
                 --user "${{ secrets.AIRFLOW_USER }}:${{ secrets.AIRFLOW_PASSWORD }}"
          done
