name: Deploy DAGs to Airflow

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload DAGs to Airflow
        run: |
          for file in dags/*.py; do
              dag_id=$(basename "$file" .py)
              echo "🔹 Running DAG: $dag_id"

              curl -X POST "${{ secrets.AIRFLOW_URL }}/api/v1/dags/$dag_id/dagRuns" \
                  -H "Content-Type: application/json" \
                  --user "${{ secrets.AIRFLOW_USER }}:${{ secrets.AIRFLOW_PASSWORD }}" \
                  --data '{"conf": {}}' \
                  -v  
              
              echo "✅ Finished processing DAG: $dag_id"
              echo "--------------------------------"
          done
