name: Deploy DAGs to Airflow

on:
  push:
    branches:
      - main  # ירוץ בכל push ל-main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload DAGs to Airflow
        run: |
          curl -X POST "${{ secrets.AIRFLOW_URL }}/api/v1/dags" \
               --user "${{ secrets.AIRFLOW_USER }}:${{ secrets.AIRFLOW_PASSWORD }}" \
               -H "Content-Type: application/json" \
               -d '{}'

      - name: Restart Airflow Scheduler
        run: |
          curl -X POST "${{ secrets.AIRFLOW_URL }}/api/v1/dags/default_dag/refresh" \
               --user "${{ secrets.AIRFLOW_USER }}:${{ secrets.AIRFLOW_PASSWORD }}"
